version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE_KAFKA://kafka:9093
      KAFKA_LISTENERS: INSIDE_KAFKA://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE_KAFKA:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE_KAFKA  # 🔥 important fix
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
